#include "render_buffer.h"
#include "letter.h"

#include <stdint.h>
#include <stdio.h>
#include <string.h>

#define BM_LETTER_H 16
#define BM_LETTER_W 16

#define X )*2+1
#define _ )*2
#define s ((((((((((((((((0

letter_row letters[][16] = {
  {
    s _ _ _ _ _ _ _ X X _ _ _ _ _ _ _ ,
    s _ _ _ _ _ X X X X X X _ _ _ _ _ ,
    s _ _ _ _ X X X X X X X X _ _ _ _ ,
    s _ _ _ X X X X _ _ X X X X _ _ _ ,
    s _ _ X X X X _ _ _ _ X X X X _ _ ,
    s _ X X X X _ _ _ _ _ _ X X X X _ ,
    s X X X X _ _ _ _ _ _ _ _ X X X X ,
    s X X X X _ _ _ _ _ _ _ _ X X X X ,
    s X X X X X X X X X X X X X X X X ,
    s X X X X X X X X X X X X X X X X ,
    s X X X X X X X X X X X X X X X X ,
    s X X X X X _ _ _ _ _ _ X X X X X ,
    s X X X X _ _ _ _ _ _ _ _ X X X X ,
    s X X X X _ _ _ _ _ _ _ _ X X X X ,
    s X X X X _ _ _ _ _ _ _ _ X X X X ,
    s X X X X _ _ _ _ _ _ _ _ X X X X ,
  },
  {
    s X X X X X X X X X X _ _ _ _ _ _ ,
    s X X X X X X X X X X X X X _ _ _ ,
    s X X X X X X X X X X X X X X X _ ,
    s X X X X _ _ _ _ _ _ _ X X X X X ,
    s X X X X _ _ _ _ _ _ _ X X X X X ,
    s X X X X _ _ _ _ _ _ _ _ X X X X ,
    s X X X X _ _ _ _ _ _ _ X X X _ _ ,
    s X X X X X X X X X X X X X _ _ _ ,
    s X X X X X X X X X X X X X _ _ _ ,
    s X X X X _ _ _ _ _ _ _ X X X X _ ,
    s X X X X _ _ _ _ _ _ _ _ X X X X ,
    s X X X X _ _ _ _ _ _ _ _ X X X X ,
    s X X X X _ _ _ _ _ _ _ X X X X X ,
    s X X X X X X X X X X X X X X X _ ,
    s X X X X X X X X X X X X X X X _ ,
    s X X X X X X X X X X X X X _ _ _ ,
  },
  {
    s _ _ _ _ _ X X X X X X X X X X X ,
    s _ _ _ X X X X X X X X X X X X X ,
    s _ X X X X X X X X X X X X X X X ,
    s X X X X X _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X X _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X X _ _ _ _ _ _ _ _ _ _ _ _ ,
    s _ X X X X X X X X X X X X X X X ,
    s _ _ X X X X X X X X X X X X X X ,
    s _ _ _ _ X X X X X X X X X X X X ,
  },
  {
    s X X X X X X X X _ _ _ _ _ _ _ _ ,
    s X X X X X X X X X _ _ _ _ _ _ _ ,
    s X X X X X X X X X X _ _ _ _ _ _ ,
    s X X X X _ _ _ X X X X _ _ _ _ _ ,
    s X X X X _ _ _ _ X X X X _ _ _ _ ,
    s X X X X _ _ _ _ _ X X X X _ _ _ ,
    s X X X X _ _ _ _ _ _ X X X X _ _ ,
    s X X X X _ _ _ _ _ _ X X X X X _ ,
    s X X X X _ _ _ _ _ _ _ X X X X X ,
    s X X X X _ _ _ _ _ _ X X X X X _ ,
    s X X X X _ _ _ _ _ X X X X X _ _ ,
    s X X X X _ _ _ _ X X X X X _ _ _ ,
    s X X X X _ _ _ X X X X X _ _ _ _ ,
    s X X X X X X X X X X X _ _ _ _ _ ,
    s X X X X X X X X X X _ _ _ _ _ _ ,
    s X X X X X X X X X _ _ _ _ _ _ _ ,
  },
  {
    s X X X X X X X X X X X X X X _ _ ,
    s X X X X X X X X X X X X X X _ _ ,
    s X X X X X X X X X X X X X X _ _ ,
    s X X X X _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X X _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X X _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X X X X X X X X X _ _ _ _ _ ,
    s X X X X X X X X X X X _ _ _ _ _ ,
    s X X X X X X X X X X X _ _ _ _ _ ,
    s X X X X _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X X _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X X _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X X _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X X X X X X X X X X X X _ _ ,
    s X X X X X X X X X X X X X X _ _ ,
    s X X X X X X X X X X X X X X _ _ ,
  },
  {
    s X X X X X X X X X X X X X X _ _ ,
    s X X X X X X X X X X X X X X _ _ ,
    s X X X X X X X X X X X X X X _ _ ,
    s X X X X _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X X _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X X _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X X _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X X X X X X X X X _ _ _ _ _ ,
    s X X X X X X X X X X X _ _ _ _ _ ,
    s X X X X _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X X _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X X _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X X _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X X _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X X _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X X _ _ _ _ _ _ _ _ _ _ _ _ ,
  },
  {
    s _ _ _ _ _ X X X X X X X X X X X ,
    s _ _ _ X X X X X X X X X X X X X ,
    s _ X X X X X X X X X X X X X X X ,
    s X X X X X X X _ _ _ _ _ _ _ _ _ ,
    s X X X X X X _ _ _ _ _ _ _ _ _ _ ,
    s X X X X X _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X X _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X X _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X X _ _ _ _ _ X X X X X X X ,
    s X X X X _ _ _ _ _ X X X X X X X ,
    s X X X X _ _ _ _ _ _ _ _ _ X X X ,
    s X X X X X _ _ _ _ _ _ _ _ X X X ,
    s X X X X X X _ _ _ _ _ _ X X X X ,
    s _ X X X X X X X X X X X X X X _ ,
    s _ _ X X X X X X X X X X X X X _ ,
    s _ _ _ _ X X X X X X X X X _ _ _ ,
  },
  {
    s X X X X _ _ _ _ _ _ _ _ X X X X ,
    s X X X X _ _ _ _ _ _ _ _ X X X X ,
    s X X X X _ _ _ _ _ _ _ _ X X X X ,
    s X X X X _ _ _ _ _ _ _ _ X X X X ,
    s X X X X _ _ _ _ _ _ _ _ X X X X ,
    s X X X X _ _ _ _ _ _ _ _ X X X X ,
    s X X X X _ _ _ _ _ _ _ _ X X X X ,
    s X X X X X X X X X X X X X X X X ,
    s X X X X X X X X X X X X X X X X ,
    s X X X X X X X X X X X X X X X X ,
    s X X X X _ _ _ _ _ _ _ _ X X X X ,
    s X X X X _ _ _ _ _ _ _ _ X X X X ,
    s X X X X _ _ _ _ _ _ _ _ X X X X ,
    s X X X X _ _ _ _ _ _ _ _ X X X X ,
    s X X X X _ _ _ _ _ _ _ _ X X X X ,
    s X X X X _ _ _ _ _ _ _ _ X X X X ,
  },
  {
    s _ _ _ X X X X X X X X X _ _ _ _ ,
    s _ _ _ X X X X X X X X X _ _ _ _ ,
    s _ _ _ _ _ _ X X X _ _ _ _ _ _ _ ,
    s _ _ _ _ _ _ X X X _ _ _ _ _ _ _ ,
    s _ _ _ _ _ _ X X X _ _ _ _ _ _ _ ,
    s _ _ _ _ _ _ X X X _ _ _ _ _ _ _ ,
    s _ _ _ _ _ _ X X X _ _ _ _ _ _ _ ,
    s _ _ _ _ _ _ X X X _ _ _ _ _ _ _ ,
    s _ _ _ _ _ _ X X X _ _ _ _ _ _ _ ,
    s _ _ _ _ _ _ X X X _ _ _ _ _ _ _ ,
    s _ _ _ _ _ _ X X X _ _ _ _ _ _ _ ,
    s _ _ _ _ _ _ X X X _ _ _ _ _ _ _ ,
    s _ _ _ _ _ _ X X X _ _ _ _ _ _ _ ,
    s _ _ _ _ _ _ X X X _ _ _ _ _ _ _ ,
    s _ _ _ X X X X X X X X X _ _ _ _ ,
    s _ _ _ X X X X X X X X X _ _ _ _ ,
  },
  {
    s _ _ _ _ _ _ X X X X X X X X X _ ,
    s _ _ _ _ _ _ X X X X X X X X X _ ,
    s _ _ _ _ _ _ _ _ _ X X X _ _ _ _ ,
    s _ _ _ _ _ _ _ _ _ X X X _ _ _ _ ,
    s _ _ _ _ _ _ _ _ _ X X X _ _ _ _ ,
    s _ _ _ _ _ _ _ _ _ X X X _ _ _ _ ,
    s _ _ _ _ _ _ _ _ _ X X X _ _ _ _ ,
    s _ _ _ _ _ _ _ _ _ X X X _ _ _ _ ,
    s _ _ _ _ _ _ _ _ _ X X X _ _ _ _ ,
    s _ _ _ _ _ _ _ _ _ X X X _ _ _ _ ,
    s _ _ _ _ _ _ _ _ _ X X X _ _ _ _ ,
    s _ X X _ _ _ _ _ _ X X X _ _ _ _ ,
    s _ X X _ _ _ _ _ _ X X X _ _ _ _ ,
    s _ X X _ _ _ _ _ _ X X X _ _ _ _ ,
    s _ X X X X X X X X X X X _ _ _ _ ,
    s _ X X X X X X X X X X X _ _ _ _ ,
  },
  {
    s X X X _ _ _ _ _ X X X X _ _ _ _ ,
    s X X X _ _ _ _ X X X X _ _ _ _ _ ,
    s X X X _ _ _ X X X X _ _ _ _ _ _ ,
    s X X X _ _ X X X X _ _ _ _ _ _ _ ,
    s X X X _ X X X X _ _ _ _ _ _ _ _ ,
    s X X X X X X X _ _ _ _ _ _ _ _ _ ,
    s X X X X X X _ _ _ _ _ _ _ _ _ _ ,
    s X X X X X _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X X X _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X X X X _ _ _ _ _ _ _ _ _ _ ,
    s X X X _ X X X _ _ _ _ _ _ _ _ _ ,
    s X X X _ _ X X X _ _ _ _ _ _ _ _ ,
    s X X X _ _ _ X X X _ _ _ _ _ _ _ ,
    s X X X _ _ _ _ X X X _ _ _ _ _ _ ,
    s X X X _ _ _ _ _ X X X _ _ _ _ _ ,
    s X X X _ _ _ _ _ _ X X X _ _ _ _ ,
  },
  {
    s X X X _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X X X X X X X X X X _ _ _ _ ,
    s X X X X X X X X X X X X _ _ _ _ ,
    s X X X X X X X X X X X X _ _ _ _ ,
  },
  {
    s X X X _ _ _ _ _ _ _ _ _ _ X X X ,
    s X X X X _ _ _ _ _ _ _ _ X X X X ,
    s X X X X X _ _ _ _ _ _ X X X X X ,
    s X X X X X X _ _ _ _ X X X X X X ,
    s X X X X X X X _ _ X X X X X X X ,
    s X X X _ X X X X X X X X _ X X X ,
    s X X X _ _ X X X X X X _ _ X X X ,
    s X X X _ _ _ X X X X _ _ _ X X X ,
    s X X X _ _ _ _ X X _ _ _ _ X X X ,
    s X X X _ _ _ _ _ _ _ _ _ _ X X X ,
    s X X X _ _ _ _ _ _ _ _ _ _ X X X ,
    s X X X _ _ _ _ _ _ _ _ _ _ X X X ,
    s X X X _ _ _ _ _ _ _ _ _ _ X X X ,
    s X X X _ _ _ _ _ _ _ _ _ _ X X X ,
    s X X X _ _ _ _ _ _ _ _ _ _ X X X ,
    s X X X _ _ _ _ _ _ _ _ _ _ X X X ,
  },
  {
    s X X X _ _ _ _ _ _ _ _ _ _ X X X ,
    s X X X X _ _ _ _ _ _ _ _ _ X X X ,
    s X X X X X _ _ _ _ _ _ _ _ X X X ,
    s X X X X X X _ _ _ _ _ _ _ X X X ,
    s X X X X X X X _ _ _ _ _ _ X X X ,
    s X X X _ X X X X _ _ _ _ _ X X X ,
    s X X X _ _ X X X X _ _ _ _ X X X ,
    s X X X _ _ _ X X X X _ _ _ X X X ,
    s X X X _ _ _ _ X X X X _ _ X X X ,
    s X X X _ _ _ _ _ X X X X _ X X X ,
    s X X X _ _ _ _ _ _ X X X X X X X ,
    s X X X _ _ _ _ _ _ _ X X X X X X ,
    s X X X _ _ _ _ _ _ _ _ X X X X X ,
    s X X X _ _ _ _ _ _ _ _ _ X X X X ,
    s X X X _ _ _ _ _ _ _ _ _ _ X X X ,
    s X X X _ _ _ _ _ _ _ _ _ _ X X X ,
  },
  {
    s _ _ X X X X X X X X X X X X _ _ ,
    s _ X X X X X X X X X X X X X X _ ,
    s X X X X X X X X X X X X X X X X ,
    s X X X X X _ _ _ _ _ _ X X X X X ,
    s X X X X _ _ _ _ _ _ _ _ X X X X ,
    s X X X _ _ _ _ _ _ _ _ _ _ X X X ,
    s X X X _ _ _ _ _ _ _ _ _ _ X X X ,
    s X X X _ _ _ _ _ _ _ _ _ _ X X X ,
    s X X X _ _ _ _ _ _ _ _ _ _ X X X ,
    s X X X _ _ _ _ _ _ _ _ _ _ X X X ,
    s X X X _ _ _ _ _ _ _ _ _ _ X X X ,
    s X X X X _ _ _ _ _ _ _ _ X X X X ,
    s X X X X X _ _ _ _ _ _ X X X X X ,
    s X X X X X X X X X X X X X X X X ,
    s _ X X X X X X X X X X X X X X _ ,
    s _ _ X X X X X X X X X X X X _ _ ,
  },
  {
    s X X X X X X X X X X X _ _ _ _ _ ,
    s X X X X X X X X X X X X _ _ _ _ ,
    s X X X X X X X X X X X X X _ _ _ ,
    s X X X _ _ _ _ _ _ _ X X X X _ _ ,
    s X X X _ _ _ _ _ _ _ _ X X X _ _ ,
    s X X X _ _ _ _ _ _ _ _ X X X _ _ ,
    s X X X _ _ _ _ _ _ _ _ X X X _ _ ,
    s X X X _ _ _ _ _ _ _ X X X X _ _ ,
    s X X X X X X X X X X X X X _ _ _ ,
    s X X X X X X X X X X X X _ _ _ _ ,
    s X X X X X X X X X X _ _ _ _ _ _ ,
    s X X X _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X _ _ _ _ _ _ _ _ _ _ _ _ _ ,
  },
  {
    s _ _ X X X X X X X X X X _ _ _ _ ,
    s _ X X X X X X X X X X X X _ _ _ ,
    s X X X X X X X X X X X X X X _ _ ,
    s X X X X X _ _ _ _ X X X X X _ _ ,
    s X X X X _ _ _ _ _ _ X X X X _ _ ,
    s X X X _ _ _ _ _ _ _ _ X X X _ _ ,
    s X X X _ _ _ _ _ _ _ _ X X X _ _ ,
    s X X X _ _ _ _ _ _ _ _ X X X _ _ ,
    s X X X _ _ _ _ _ _ _ _ X X X _ _ ,
    s X X X _ _ _ _ X X _ _ X X X _ _ ,
    s X X X _ _ _ _ X X X _ X X X _ _ ,
    s X X X X _ _ _ _ X X X X X X _ _ ,
    s X X X X X _ _ _ _ X X X X X _ _ ,
    s X X X X X X X X X X X X X X _ _ ,
    s _ X X X X X X X X X X X X X X X ,
    s _ _ X X X X X X X X X X _ X X X ,
  },
  {
    s X X X X X X X X X X X _ _ _ _ _ ,
    s X X X X X X X X X X X X _ _ _ _ ,
    s X X X X X X X X X X X X X _ _ _ ,
    s X X X _ _ _ _ _ _ _ X X X X _ _ ,
    s X X X _ _ _ _ _ _ _ _ X X X _ _ ,
    s X X X _ _ _ _ _ _ _ _ X X X _ _ ,
    s X X X _ _ _ _ _ _ _ _ X X X _ _ ,
    s X X X _ _ _ _ _ _ _ X X X X _ _ ,
    s X X X X X X X X X X X X X _ _ _ ,
    s X X X X X X X X X X X X _ _ _ _ ,
    s X X X X X X X X X X X _ _ _ _ _ ,
    s X X X _ _ _ _ _ X X X X _ _ _ _ ,
    s X X X _ _ _ _ _ _ X X X X _ _ _ ,
    s X X X _ _ _ _ _ _ _ X X X X _ _ ,
    s X X X _ _ _ _ _ _ _ _ X X X X _ ,
    s X X X _ _ _ _ _ _ _ _ _ X X X X ,
  },
  {
    s _ _ _ X X X X X X X X X X X X X ,
    s _ _ X X X X X X X X X X X X X X ,
    s _ X X X X X X X X X X X X X X X ,
    s X X X X _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X X _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X X _ _ _ _ _ _ _ _ _ _ _ _ ,
    s _ X X X X X X X X X X X _ _ _ _ ,
    s _ _ _ X X X X X X X X X X X _ _ ,
    s _ _ _ _ X X X X X X X X X X X _ ,
    s _ _ _ _ _ _ _ _ _ _ _ _ X X X X ,
    s _ _ _ _ _ _ _ _ _ _ _ _ _ X X X ,
    s _ _ _ _ _ _ _ _ _ _ _ _ _ X X X ,
    s _ _ _ _ _ _ _ _ _ _ _ _ X X X X ,
    s X X X X X X X X X X X X X X X _ ,
    s X X X X X X X X X X X X X X _ _ ,
    s X X X X X X X X X X X X X _ _ _ ,
  },
  {
    s X X X X X X X X X X X X X X X X ,
    s X X X X X X X X X X X X X X X X ,
    s X X X X X X X X X X X X X X X X ,
    s X X X X X X X X X X X X X X X X ,
    s _ _ _ _ _ X X X X X X _ _ _ _ _ ,
    s _ _ _ _ _ X X X X X X _ _ _ _ _ ,
    s _ _ _ _ _ X X X X X X _ _ _ _ _ ,
    s _ _ _ _ _ X X X X X X _ _ _ _ _ ,
    s _ _ _ _ _ X X X X X X _ _ _ _ _ ,
    s _ _ _ _ _ X X X X X X _ _ _ _ _ ,
    s _ _ _ _ _ X X X X X X _ _ _ _ _ ,
    s _ _ _ _ _ X X X X X X _ _ _ _ _ ,
    s _ _ _ _ _ X X X X X X _ _ _ _ _ ,
    s _ _ _ _ _ X X X X X X _ _ _ _ _ ,
    s _ _ _ _ _ X X X X X X _ _ _ _ _ ,
    s _ _ _ _ _ X X X X X X _ _ _ _ _ ,
  },
  {
    s X X X _ _ _ _ _ _ _ _ _ _ X X X ,
    s X X X _ _ _ _ _ _ _ _ _ _ X X X ,
    s X X X _ _ _ _ _ _ _ _ _ _ X X X ,
    s X X X _ _ _ _ _ _ _ _ _ _ X X X ,
    s X X X _ _ _ _ _ _ _ _ _ _ X X X ,
    s X X X _ _ _ _ _ _ _ _ _ _ X X X ,
    s X X X _ _ _ _ _ _ _ _ _ _ X X X ,
    s X X X _ _ _ _ _ _ _ _ _ _ X X X ,
    s X X X _ _ _ _ _ _ _ _ _ _ X X X ,
    s X X X _ _ _ _ _ _ _ _ _ _ X X X ,
    s X X X _ _ _ _ _ _ _ _ _ _ X X X ,
    s X X X X _ _ _ _ _ _ _ _ X X X X ,
    s X X X X X _ _ _ _ _ _ X X X X X ,
    s X X X X X X X X X X X X X X X X ,
    s _ X X X X X X X X X X X X X X _ ,
    s _ _ X X X X X X X X X X X X _ _ ,
  },
  {
    s X X X X _ _ _ _ _ _ _ _ X X X X ,
    s X X X X _ _ _ _ _ _ _ _ X X X X ,
    s X X X X _ _ _ _ _ _ _ _ X X X X ,
    s X X X X _ _ _ _ _ _ _ _ X X X X ,
    s X X X X _ _ _ _ _ _ _ _ X X X X ,
    s X X X X _ _ _ _ _ _ _ _ X X X X ,
    s X X X X _ _ _ _ _ _ _ _ X X X X ,
    s X X X X _ _ _ _ _ _ _ _ X X X X ,
    s X X X X _ _ _ _ _ _ _ _ X X X X ,
    s _ X X X X _ _ _ _ _ _ X X X X _ ,
    s _ _ X X X X _ _ _ _ X X X X _ _ ,
    s _ _ _ X X X X _ _ X X X X _ _ _ ,
    s _ _ _ _ X X X X X X X X _ _ _ _ ,
    s _ _ _ _ _ X X X X X X _ _ _ _ _ ,
    s _ _ _ _ _ _ X X X X _ _ _ _ _ _ ,
    s _ _ _ _ _ _ _ X X _ _ _ _ _ _ _ ,
  },
  {
    s X X X _ _ _ _ _ _ _ _ _ _ X X X ,
    s X X X _ _ _ _ _ _ _ _ _ _ X X X ,
    s X X X _ _ _ _ _ _ _ _ _ _ X X X ,
    s X X X _ _ _ _ _ _ _ _ _ _ X X X ,
    s X X X _ _ _ _ _ _ _ _ _ _ X X X ,
    s X X X _ _ _ _ _ _ _ _ _ _ X X X ,
    s X X X _ _ _ _ _ _ _ _ _ _ X X X ,
    s X X X _ _ _ _ X X _ _ _ _ X X X ,
    s X X X _ _ _ X X X X _ _ _ X X X ,
    s X X X _ _ X X X X X X _ _ X X X ,
    s X X X _ X X X X X X X X _ X X X ,
    s X X X X X X X _ _ X X X X X X X ,
    s X X X X X X _ _ _ _ X X X X X X ,
    s X X X X X _ _ _ _ _ _ X X X X X ,
    s X X X X _ _ _ _ _ _ _ _ X X X X ,
    s X X X _ _ _ _ _ _ _ _ _ _ X X X ,
  },
  {
    s X X X _ _ _ _ _ _ _ _ _ _ X X X ,
    s X X X X _ _ _ _ _ _ _ _ X X X X ,
    s _ X X X X _ _ _ _ _ _ X X X X _ ,
    s _ _ X X X X _ _ _ _ X X X X _ _ ,
    s _ _ _ X X X X _ _ X X X X _ _ _ ,
    s _ _ _ _ X X X X X X X X _ _ _ _ ,
    s _ _ _ _ _ X X X X X X _ _ _ _ _ ,
    s _ _ _ _ _ _ X X X X _ _ _ _ _ _ ,
    s _ _ _ _ _ X X X X X X _ _ _ _ _ ,
    s _ _ _ _ X X X X X X X X _ _ _ _ ,
    s _ _ _ X X X X _ _ X X X X _ _ _ ,
    s _ _ X X X X _ _ _ _ X X X X _ _ ,
    s _ X X X X _ _ _ _ _ _ X X X X _ ,
    s X X X X _ _ _ _ _ _ _ _ X X X X ,
    s X X X _ _ _ _ _ _ _ _ _ _ X X X ,
    s X X _ _ _ _ _ _ _ _ _ _ _ _ X X ,
  },
  {
    s X X X _ _ _ _ _ _ _ _ _ _ X X X ,
    s X X X X _ _ _ _ _ _ _ _ X X X X ,
    s _ X X X X _ _ _ _ _ _ X X X X _ ,
    s _ _ X X X X _ _ _ _ X X X X _ _ ,
    s _ _ _ X X X X _ _ X X X X _ _ _ ,
    s _ _ _ _ X X X X X X X X _ _ _ _ ,
    s _ _ _ _ _ X X X X X X _ _ _ _ _ ,
    s _ _ _ _ _ _ X X X X _ _ _ _ _ _ ,
    s _ _ _ _ _ X X X X _ _ _ _ _ _ _ ,
    s _ _ _ _ X X X X _ _ _ _ _ _ _ _ ,
    s _ _ _ X X X X _ _ _ _ _ _ _ _ _ ,
    s _ _ X X X X _ _ _ _ _ _ _ _ _ _ ,
    s _ X X X X _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X X _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s X X _ _ _ _ _ _ _ _ _ _ _ _ _ _ ,
  },
  {
    s X X X X X X X X X X X X X X X _ ,
    s X X X X X X X X X X X X X X X _ ,
    s X X X X X X X X X X X X X X X _ ,
    s _ _ _ _ _ _ _ _ _ _ X X X X _ _ ,
    s _ _ _ _ _ _ _ _ _ X X X X _ _ _ ,
    s _ _ _ _ _ _ _ _ X X X X _ _ _ _ ,
    s _ _ _ _ _ _ _ X X X X _ _ _ _ _ ,
    s _ _ _ _ _ _ X X X X _ _ _ _ _ _ ,
    s _ _ _ _ _ X X X X _ _ _ _ _ _ _ ,
    s _ _ _ _ X X X X _ _ _ _ _ _ _ _ ,
    s _ _ _ X X X X _ _ _ _ _ _ _ _ _ ,
    s _ _ X X X X _ _ _ _ _ _ _ _ _ _ ,
    s _ X X X X _ _ _ _ _ _ _ _ _ _ _ ,
    s X X X X X X X X X X X X X X X X ,
    s X X X X X X X X X X X X X X X X ,
    s X X X X X X X X X X X X X X X X ,
  },
  {
    s _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ,
    s _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ ,
  },
};

#undef X
#undef _
#undef s

void letter_print(uint32_t *render_buf, char ch, int x, int y, int w, int h) {
  letter_row *letter = letters[ch - 65];
  for (int row = 0; row < h; ++row) {
    if (row + y < 0 || row + y > RENDER_BUF_H)
      continue;
    for (int col = 0; col < w; ++col) {
      if (col + x < 0 || col + x > RENDER_BUF_W)
        continue;
      int r = ((float)row/h) * BM_LETTER_H;
      int c = ((float)col/w) * BM_LETTER_W;
      uint32_t pixel = ((letter[r] >> (sizeof(letter_row)*8 - 1 - c)) & 0x1) ? 0xFF0000
                                                                             : 0x000000;
      if (pixel)
        render_buf[(row + y) * RENDER_BUF_W + (col + x)] = pixel;
    }
  }
}

void text_print(uint32_t *render_buf, char *text, struct text_opts *opts) {
  for (int i = 0; i < strlen(text); ++i) {
    if (text[i] == ' ')
      continue;
    letter_print(render_buf, text[i],
                 opts->x + (opts->ch_width + opts->spacing) * i, 0,
                 opts->ch_width, opts->ch_height);
  }
}
